

enhancement:
  item:
    name: "%item_name% [%item_level_prefix%%item_level%]"
    lore:
      stats_damage: "Sát thương cơ bản: %basic_damage% ( +%enhance_damage% )"
      stats_armor: "Giáp cơ bản: %basic_armor% ( +%enhance_armor% )"
      stats_health: "Máu cơ bản: %basic_health% ( +%enhance_health% )"

broadcast_success_after_level: 8

level:
  '1':
    success_chance: 100
    armor_increase: 1
    weapon_increase: 1

  '2':
    success_chance: 80
    armor_increase: 1
    weapon_increase: 1

  '3':
    success_chance: 70
    armor_increase: 1
    weapon_increase: 1

  '4':
    success_chance: 60
    weapon_increase: 1
    armor_increase: 1

  '5':
    success_chance: 55
    armor_increase: 1
    weapon_increase: 1

  '6':
    success_chance: 50
    armor_increase: 5
    weapon_increase: 5

  '7':
    success_chance: 45
    armor_increase: 5
    weapon_increase: 5

  '8':
    success_chance: 40
    armor_increase: 5
    weapon_increase: 5

  '9':
    success_chance: 35
    armor_increase: 5
    weapon_increase: 5

  '10':
    success_chance: 30
    armor_increase: 10
    weapon_increase: 10

  '11':
    success_chance: 25
    armor_increase: 10
    weapon_increase: 10

  '12':
    success_chance: 20
    armor_increase: 10
    weapon_increase: 10

  '13':
    success_chance: 15
    armor_increase: 15
    weapon_increase: 15

  '14':
    success_chance: 10
    armor_increase: 15
    weapon_increase: 15

  '15':
    success_chance: 5
    armor_increase: 20
    weapon_increase: 20

message_prefix: "[&6&lVinaMC&r] "

message:
  enhance_success: "&aCường hóa thành công"
  enhance_failed: "&cCường hóa thất bại"
  command_doesnt_exists: "&4Lệnh không tồn tại"
  command_invalid: "&4Lệnh không hợp lệ"
  command_must_send_ingame: "&4chỉ thực hiện được lệnh này trong game"
  missing_permission: "&4Thiếu quyền sử dụng lệnh này."
  hand_empty: "&3Hãy giữ item trên tay để dùng lệnh này"
  invalid_data_type: "&cTham số không hợp lệ"
  number_must_positive: "&cTham số không được nhỏ hơn 0"
  broadcast_success_message: "&2Chúc mừng %player_name% cường hóa thành công %item_name%&r lên cấp %item_level%"

  command:
    create_stone: "Dùng /setstone"
    create_charm: "Dùng /setcharm"
    create_powder: "Dùng /setpowder <rate_percent>"