main: dev.iqux.rpgpack.App
name: RPGPack
author: HlV_Is_Me
descriptions: hehe rpg plugin brrr
version: 0.1

commands:
  createstone:
    aliases: [cstone]
    descriptions: Create stone for enchance some thing like armor, weapon, whatever is it