main: dev.iqux.vina.App
name: VinaPack
author: HlV_Is_Me
descriptions: vina pack plugin
version: 2.0.8
depend: [NBTAPI]
softdepends: [MVdWPlaceholderAPI]

commands:
  vina:
    aliases: [vn]
    descriptions: Base command

permissions:
  vina.admin:
    description: Gives access to everything!
    children:
      vina.command.enchance.show: true
      vina.command.enchance.setlucky: true
      vina.command.enchance.setstone: true
      vina.command.enchance.setprotector: true
      vina.command.enchance.setbasicarmor: true
      vina.command.enchance.setbasicdamage: true
      vina.command.enchance.setbasichealth: true
      vina.command.plugin.reload: true
