main: dev.iqux.vina.App
name: VinaPack
author: HlV_Is_Me
descriptions: vina pack plugin
version: 0.1
depend: [NBTAPI]

commands:
  setstone:
    aliases: [ss]
    descriptions: Set stone for enchance some thing like armor, weapon, whatever is it
  setcharm:
    aliases: [sc]
    descriptions: Set charm for protect stats of item
  setpowder:
    aliases: [sl]
    descriptions: Set lucky powder for increase percent rate success when enchance
  showenhance:
    aliases: [cuonghoa]
    descriptions: enchance gui