main: dev.iqux.vina.App
name: VinaPack
author: HlV_Is_Me
descriptions: vina pack plugin
version: 0.1
depend: [NBTAPI]

commands:
  vina:
    aliases: [vn]
    descriptions: Base command

permissions:
  vina.admin:
    description: Gives access to everything!
    children:
      vina.command.enchance.createstone: true